### ISSUE TITLE
Target Java 8

### ISSUE THREAD

**Issue by daniel-shuy** [cosmin-marginean/alkemy#1]
Thanks for this great framework!

Just one suggestion, could you target Java `8` instead of Java `17`? i.e.
```groovy
// build.gradle

kotlin {
    jvmToolchain(8)
}
```

Kotlin targets Java 8 by default (https://kotlinlang.org/docs/faq.html#which-versions-of-jvm-does-kotlin-target), and this prevents projects that target Java <17 from using this amazing framework

**Comment by cosmin-marginean** [comment]
I'm glad you found it useful!
Yes, this was actually an oversight. Version 0.8.5 is now targeting Java 8. Should be in Maven Central in the next half an hour or so.

**Comment by daniel-shuy** [comment]
That's fast, thank you!
