### ISSUE TITLE
Spring Boot integration

### ISSUE THREAD

**Issue by daniel-shuy** [cosmin-marginean/alkemy#2]
Thanks again for this amazing project!

I'm trying to use Alkemy with Spring Boot (`@SpringBootTest`), to pass the randomized Spring Boot web server port (`local.server.port`) as `alkemy.baseUrl`. But I'm unable to do so because the constructor extension is run before Spring Boot is initialized.

Can I contribute a module to integrate Alkemy with Spring Boot? To get the `AlkemyConfig` from a Spring `@ConfigurationProperties` instead of system properties?

**Comment by cosmin-marginean** [comment]
I can see another module (maybe separate library in this repo) that we can consider for these purposes, but I would want to keep external dependencies like Spring outside the scope of the core library. The reason being that we don't want to prescribe what framework should be used with Alkemy (and deal with Spring version conflicts etc).

A separate lib however would be a bigger piece here, and I'm happy to review a PR, but it would require a restructuring of the project as well (currently it all sits as one library, and no submodules, which probably isn't ideal, but it's the current status).

But back to your specific issue, I _believe_ you might be able to achieve this by using a custom config, where you'd be able to inject the Spring Boot configuration properties. There is an example for this here which shows how to run the browser with a custom config: https://github.com/cosmin-marginean/alkemy/blob/main/src/test/kotlin/io/alkemy/examples/CustomConfig.kt

**Comment by daniel-shuy** [comment]
> I can see another module (maybe separate library in this repo) that we can consider for these purposes, but I would want to keep external dependencies like Spring outside the scope of the core library. The reason being that we don't want to prescribe what framework should be used with Alkemy (and deal with Spring version conflicts etc).

> A separate lib however would be a bigger piece here, and I'm happy to review a PR, but it would require a restructuring of the project as well (currently it all sits as one library, and no submodules, which probably isn't ideal, but it's the current status).

I agree, it should be a separate module. Its not that difficult to convert the project to a multi-project build. To be honest, I've already done it and even implemented the `alkemy-spring` module, I just need to add tests and documentation for it.

> But back to your specific issue, I believe you might be able to achieve this by using a custom config, where you'd be able to inject the Spring Boot configuration properties. There is an example for this here which shows how to run the browser with a custom config: https://github.com/cosmin-marginean/alkemy/blob/main/src/test/kotlin/io/alkemy/examples/CustomConfig.kt

Yup, that's the idea. I'm also thinking of utilizing [kotest-extension-spring](https://kotest.io/docs/extensions/spring.html) to inject the `AlkemyContext` in the constructor (together with other Spring beans).

I'll have to refactor `AlkemyConfig`'s `companion object` to not eagerly initialize an instance of `AlkemyConfig` though:
https://github.com/cosmin-marginean/alkemy/blob/c2c693b58bd7735bb3d2dbd12e5450193a00afdc/src/main/kotlin/io/alkemy/config/AlkemyConfig.kt#L26-L28
